class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.95.tar.gz"
  sha256 "3f1e9ed0668d07b0dbb9ca82d87f5ffe32129428a0b25291c85b5829843e0d83"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "65a1858d229f36e5c4a6cf0aa13cdf19a63a259569c3d7161d905e94807349bd"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "65a1858d229f36e5c4a6cf0aa13cdf19a63a259569c3d7161d905e94807349bd"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "65a1858d229f36e5c4a6cf0aa13cdf19a63a259569c3d7161d905e94807349bd"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "61bc9b396d694a0de9f0dc30c0e0c20c2f083e096b83104f50db62f118f6f4d8"
    sha256 cellar: :any,                 x86_64_linux:      "bffe24d849d8bcb8d66f309af34fb275449724480facb779491cdb6283457919"
  end

  depends_on "go" => :build

  deny_network_access!

  def fetch
    system "go", "mod", "download"
  end

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
