class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v3.6.109.tar.gz"
  sha256 "12685925203aefd7ee68aba16e1230d706289356c89b1653e4da21360ee7cf96"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_golden_gate: "a04e223de600891e26a43a57ff5b109570b189f1799be14c3f5093836ae8e6d2"
    sha256 cellar: :any_skip_relocation, arm64_tahoe:       "a04e223de600891e26a43a57ff5b109570b189f1799be14c3f5093836ae8e6d2"
    sha256 cellar: :any_skip_relocation, arm64_sequoia:     "a04e223de600891e26a43a57ff5b109570b189f1799be14c3f5093836ae8e6d2"
    sha256 cellar: :any_skip_relocation, arm64_linux:       "a1ba32293838c6be62fb03ddecfeab850acb6a054481b133f08e142377454672"
    sha256 cellar: :any,                 x86_64_linux:      "0d4e95eba33ccca3c0a52f954183a1908ca2a0c28a4ec643c687b1aff717e88a"
  end

  depends_on "go" => :build

  deny_network_access!

  def fetch
    system "go", "mod", "download"
  end

  def install
    system "go", "build", *std_go_args(ldflags: "-X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
